version: '3'

volumes:
  postgres-data:
  gems:
  redis-data:

services:
  redis:
    image: redis:5.0
    command: redis-server --requirepass r3d1spass
    ports:
    - 6379:6379
    volumes:
    - redis-data:/data

  sidekiq:
    depends_on:
      - 'db'
      - 'redis'
    image: the-all-god-web
    command: sidekiq -C config/sidekiq.yml
    volumes:
      - '.:/myapp'
      - gems:/usr/local/bundle
    env_file:
      - '.env'

  db:
    image: postgres:14.5
    volumes:
      - postgres-data:/var/lib/postgresql/data
    environment:
      POSTGRES_PASSWORD: Pa33w0rd!

  web:
    build: .
    command: bash -c "rm -f tmp/pids/server.pid && bundle exec rails s -p 3000 -b '0.0.0.0'"
    entrypoint: /usr/src/app/entrypoint.sh
    stdin_open: true
    tty: true
    working_dir: /usr/src/app
    volumes:
      - .:/usr/src/app
      - gems:/usr/local/bundle
    ports:
      - "3000:3000"
    depends_on:
      - db
      #- redis
      #- sidekiq
    env_file:
      - .env
